### ISSUE TITLE
How can I use HDR-VQM for HDR video?

### ISSUE THREAD

**Issue by klob** [mperreir/HDR-VQM#1]
If I have HDR reference video and test video which's format is MP4, how can I use HDR-VAM to evaluate their quality?

**Comment by klob** [comment]
Is there get .hdr file and .exr file from hdr mp4 video?

**Comment by mperreir** [comment]
Hello, 
HDR VQM only processes video frames. So you need to extract all the frames of your MP4 video before processing it. You can do it for example with FFMPEG (I guess it is HDR-10 MP4).

**Comment by klob** [comment]
Yes, the video file I want to test is HDR-10 video file.Sadly, I found no way to convert MP4 video files to .hdr or .exr files in ffmpeg.I want to know where is the video produced by HDR-VQM for evaluating the quality of video files. Produced by camera? Or is it converted from other jpg?

**Comment by mperreir** [comment]
You question is not directly linked with HDR-VQM. As already said, HDR VQM processes only (sequences of) images in .HDR or .EXR format. Those images should contain linearly encoded (display processed, that is to say containing luminance values that correspond to what the observer sees (cd/m2 values)) luminance values (raw value), not gamma curve or other perceptual mapping curve (but this is usually the case for .HDR or .EXR images).
If your source content is an HDR-10 MP4 (h264 or h265 codec I guess) it is your responsibility to convert it to a series of HDR frames. This might be done for example y extracting TIFF frames (16 bits per channel) from your video and then converting TIFF16 to .HDR. See for example https://video.stackexchange.com/questions/22136/convert-video-to-10-bit-images for converting your video to TIFF frames.
