### ISSUE TITLE
can't find the function hdrimread and exrread

### ISSUE THREAD

**Issue by kobehuai** [mperreir/HDR-VQM#2]
hello, when I set the **cfg_hdrvqm.do_adapt** in cfg_hdrvqm.m to 'linear', it can't find the hdrimread/exrread function in adapt_display_hdrvqm.m line 42/44. Can you  help me solve this question ?

And where can I get your in-house HDR video database to repeat the experiments ?

**Comment by mperreir** [comment]
Hello,
See #3
