### ISSUE TITLE
RemoveSpecials

### ISSUE THREAD

**Issue by Dounia18** [mperreir/HDR-VQM#3]
Hello, 
I'm running the code using Matlab R2022b. There are some functions that I could not find like lum and RemoveSpecials.
If you could please give me a reference to it so that I can run the metric for my experimentations.

**Comment by mperreir** [comment]
Hello,
The readme file is missing a paragraph about the dependencies of this code. Here it is (I'll also add it to the README file)

This code depends on hdrtoolbox (https://github.com/banterle/HDR_Toolbox) and HDRITools version 0.4 (https://github.com/edgarv/hdritools ). They must be installed and added to you matlab path for this code to run fine (hdrtoolbox for HDR files opening and HDRITools for EXR files opening).

The code was written some time ago with HDRITools v0.4, maybe v0.5 (latest version) is also ok, but it is untested.
